### ISSUE TITLE
JUST MONIKA

### ISSUE THREAD

**Issue by xXBuilderBXx** [NatsukiBot/Natsuki#1]
J̙̻̤͎̣̜̭͋̓ͦ̉̍̍́U̗͈̰̜͙̤̫ͬͦ̎̋́S̰͕ͤ̊͐͐̓ͪ̎Ṫ̃ ͇͕M̙͕̮̥̎̃̂̑́O̧ͣ̽ͪ͐̂N̸̉̈́Į͊̾̾͐͋̑K͋̋̈ͨ̔̽̄҉A̡͚̫̣͍ͦ

**Comment by ohlookitsAugust** [comment]
please
